apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: import-existing-app-envelope-catalog
  title: Import Existing App to Catalog Envelope
  description: Import existing application, autocreate config-info.yaml and conditionally setup techdocs.
  tags:
    - import
    - catalog
    - register
spec:
  owner: parasol-authors
  system: parasol-rhdh
  type: template

  parameters:
    - title: Provide information about Uber Catalog
      required:
        - gitlabHost
        - envelopeGitlabOrganization
        - envelopeRepositoryName
      properties:
        gitlabHost:
          title: Gitlab hostname
          type: string
          description: Your gitlab
          default: {{ gitlab_host }}
            enum:
              - {{ gitlab_host }}
        envelopeGitlabOrganization:
          title: GitLab Organization
          type: string
          default: {{ gitlab_destination_group }}
            enum:
              - {{ gitlab_destination_group }}
        envelopeRepositoryName:
          title: Repository name
          type: string
          description: Please ensure this repo exists

    - title: Provide information about your existing app
      required:
        - gitlabOrganization
        - repositoryName
      properties:
        gitlabOrganization:
          title: GitLab Organization
          type: string
          default: {{ gitlab_destination_group }}
            enum:
              - {{ gitlab_destination_group }}
        repositoryName:
          title: Repository name
          type: string
          description: Please ensure this repo exists

    - title: Provide information about the new component for your existing app
      required:
        - componentOwner
        - componentType
        - componentLifecycle
      properties:
        componentName:
          title: Component Name
          type: string
          description: Name of the component. (Defaults to the repo name)
          default: 
        componentOwner:
          title: Owner
          description: Select an owner from the list or enter a reference to a Group or a User
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        componentType:
          title: Type
          type: string
          description: 'The type of component. Well-known and common values: service, website, library.'
          default: service
        description:
          title: A short description of this component
          type: string
        addTechDocs:
          title: Check to add TechDocs
          type: boolean  
        componentLifecycle:
          title: Lifecycle
          type: string
          description: 'The lifecycle state of the component. Well-known and common values: experimental, production, deprecated.'
          default: experimental

  steps:
  

    - id: fetch-envelope=repo
      name: Fetch envelope catalog repo
      action: fetch:template
      targetPath: ../.
      input:
        url: https://${{ parameters.gitlabHost }}/${{ parameters.gitlabOrganization }}/${{ parameters.envelopeRepositoryName }}
        
    - id: append-file
      name: Append To File Or Create New
      action: roadiehq:utils:fs:append
      input:
        path: ./envelope.yaml
        content: "\n    - https://${{ parameters.gitlabHost }}/${{ parameters.gitlabOrganization }}/${{ parameters.envelopeRepositoryName }}/-/blob/main/${{ parameters.repositoryName }}/catalog-info.yaml"

    # Merge envelope  into EXISTING repo  - only EXISTING REPO
    - id: publishUberCatalogMergeRequest
      name: Open PR with envelope.yaml
      action: publish:gitlab:merge-request
      input: 
        repoUrl: ${{ parameters.gitlabHost }}?repo=${{ parameters.envelopeRepositoryName }}&owner=${{ parameters.envelopeGitlabOrganization }}
        commitMessage: Commit for component ${{ parameters.componentName }}
        title: Open PR for update to Uber catalog
        description: Open PR with catalog-info.yaml
        sourcePath: ./
        targetPath: ./
        commitAction: update
        branchName: envelope-${{ parameters.componentName }}-update
        removeSourceBranch: true


    # Step2: Create catalog-info file for the component
    - id: catalogTemplate
      name: Fetch catalog-info  template
      action: fetch:template
      input:
        url: ./templates
        targetPath: ./patch
        values:
          applicationType: ${{ parameters.componentType }}
          component_id: ${{ parameters.componentName }}
          componentName: ${{ parameters.componentName }}
          componentLifecycle: ${{ parameters.componentLifecycle }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.gitlabHost }}/${{ parameters.gitlabOrganization }}/${{ parameters.repositoryName }}
          host: ${{ parameters.gitlabHost }}
          owner: ${{ parameters.componentOwner }}
          orgName: ${{ parameters.gitlabOrganization }}
          repoName: ${{ parameters.repositoryName }}

    
    # Merge catalog-info and techdocs into EXISTING repo   - only EXISTING REPO
    - id: publishComponentMergeRequest
      name: Open PR with for all-catalog
      action: publish:gitlab:merge-request
      input: 
        repoUrl: ${{ parameters.gitlabHost }}?repo=${{ parameters.envelopeRepositoryName }}&owner=${{ parameters.envelopeGitlabOrganization }}
        title: Open PR with catalog-info.yaml
        description: Open PR with catalog-info.yaml
        branchName: ${{ parameters.componentName }}-create
        sourcePath: ./patch
        targetPath: ./${{ parameters.componentName }}
        commitAction: create
        removeSourceBranch: true    


  

  output:
    links:
      - url: ${{ steps.publishComponentMergeRequest.output.mergeRequestUrl }}
        title: 'Component merge request'
      - url: ${{ steps.publishUberCatalogMergeRequest.output.mergeRequestUrl }}
        title: 'Uber catalog update merge request'
  